import { IInventoryItem } from 'entities/Inventory/model/types/types';

export const inventoryMockData: IInventoryItem[] = [
  {
    id: '1',
    SOID: '1',
    title: 'Portable kitchen stove',
    description: 'Portable kitchen stove for cooking',
    quantity: 10,
    price: 50,
    totalPrice: 500,
    category: 'kitchen',
  },
  {
    id: '2',
    SOID: '1',
    title: 'Tent set',
    description: 'Tent set for outdoor use',
    quantity: 5,
    price: 150,
    totalPrice: 750,
    category: 'tools',
  },
  {
    id: '3',
    SOID: '1',
    title: 'Chair',
    description: 'Chair for outdoor use',
    quantity: 15,
    price: 20,
    totalPrice: 300,
    category: 'common',
  },
  {
    id: '4',
    SOID: '2',
    title: 'Newest gadget',
    description: 'Latest technology gadget',
    quantity: 8,
    price: 200,
    totalPrice: 1600,
    category: 'newest',
  },
  {
    id: '5',
    SOID: '2',
    title: 'Kitchen Knife Set',
    description: 'Sharp kitchen knives',
    quantity: 20,
    price: 30,
    totalPrice: 600,
    category: 'kitchen',
  },
  {
    id: '6',
    SOID: '2',
    title: 'Hammer',
    description: 'Heavy-duty hammer',
    quantity: 12,
    price: 25,
    totalPrice: 300,
    category: 'tools',
  },
  {
    id: '7',
    SOID: '3',
    title: 'Electric Drill',
    description: 'Cordless electric drill',
    quantity: 7,
    price: 100,
    totalPrice: 700,
    category: 'tools',
  },
  {
    id: '8',
    SOID: '3',
    title: 'Blender',
    description: 'High-speed blender',
    quantity: 14,
    price: 80,
    totalPrice: 1120,
    category: 'kitchen',
  },
  {
    id: '9',
    SOID: '3',
    title: 'Camping Lantern',
    description: 'LED camping lantern',
    quantity: 10,
    price: 40,
    totalPrice: 400,
    category: 'tools',
  },
  {
    id: '10',
    SOID: '4',
    title: 'Smartphone',
    description: 'Latest model smartphone',
    quantity: 6,
    price: 500,
    totalPrice: 3000,
    category: 'newest',
  },
  {
    id: '11',
    SOID: '4',
    title: 'Backpack',
    description: 'Durable hiking backpack',
    quantity: 9,
    price: 60,
    totalPrice: 540,
    category: 'common',
  },
  {
    id: '12',
    SOID: '4',
    title: 'Water Filter',
    description: 'Portable water filter',
    quantity: 15,
    price: 35,
    totalPrice: 525,
    category: 'tools',
  },
  {
    id: '13',
    SOID: '5',
    title: 'Microwave Oven',
    description: 'High-efficiency microwave oven',
    quantity: 4,
    price: 120,
    totalPrice: 480,
    category: 'kitchen',
  },
  {
    id: '14',
    SOID: '5',
    title: 'Fitness Tracker',
    description: 'Wearable fitness tracker',
    quantity: 20,
    price: 90,
    totalPrice: 1800,
    category: 'newest',
  },
  {
    id: '15',
    SOID: '5',
    title: 'Cookware Set',
    description: 'Non-stick cookware set',
    quantity: 10,
    price: 100,
    totalPrice: 1000,
    category: 'kitchen',
  },
  {
    id: '16',
    SOID: '6',
    title: 'Screwdriver Set',
    description: 'Precision screwdriver set',
    quantity: 18,
    price: 25,
    totalPrice: 450,
    category: 'tools',
  },
  {
    id: '17',
    SOID: '6',
    title: 'Headlamp',
    description: 'Bright LED headlamp',
    quantity: 10,
    price: 30,
    totalPrice: 300,
    category: 'common',
  },
  {
    id: '18',
    SOID: '6',
    title: 'Wireless Earbuds',
    description: 'Noise-cancelling wireless earbuds',
    quantity: 12,
    price: 120,
    totalPrice: 1440,
    category: 'newest',
  },
  {
    id: '19',
    SOID: '7',
    title: 'Coffee Maker',
    description: 'Programmable coffee maker',
    quantity: 7,
    price: 70,
    totalPrice: 490,
    category: 'kitchen',
  },
  {
    id: '20',
    SOID: '7',
    title: 'Tent',
    description: 'Waterproof camping tent',
    quantity: 5,
    price: 150,
    totalPrice: 750,
    category: 'tools',
  },
  {
    id: '21',
    SOID: '7',
    title: 'Flashlight',
    description: 'High-powered flashlight',
    quantity: 15,
    price: 25,
    totalPrice: 375,
    category: 'common',
  },
  {
    id: '22',
    SOID: '8',
    title: 'Smartwatch',
    description: 'Multi-functional smartwatch',
    quantity: 8,
    price: 200,
    totalPrice: 1600,
    category: 'newest',
  },
  {
    id: '23',
    SOID: '8',
    title: 'Grill',
    description: 'Outdoor BBQ grill',
    quantity: 6,
    price: 300,
    totalPrice: 1800,
    category: 'kitchen',
  },
  {
    id: '24',
    SOID: '8',
    title: 'Pocket Knife',
    description: 'Multi-tool pocket knife',
    quantity: 20,
    price: 15,
    totalPrice: 300,
    category: 'tools',
  },
  {
    id: '25',
    SOID: '9',
    title: 'Power Bank',
    description: 'High-capacity power bank',
    quantity: 10,
    price: 50,
    totalPrice: 500,
    category: 'newest',
  },
  {
    id: '26',
    SOID: '9',
    title: 'Cooler Box',
    description: 'Large cooler box',
    quantity: 8,
    price: 100,
    totalPrice: 800,
    category: 'common',
  },
  {
    id: '27',
    SOID: '9',
    title: 'Kitchen Scale',
    description: 'Digital kitchen scale',
    quantity: 12,
    price: 25,
    totalPrice: 300,
    category: 'kitchen',
  },
  {
    id: '28',
    SOID: '10',
    title: 'Tablet',
    description: '10-inch tablet',
    quantity: 6,
    price: 250,
    totalPrice: 1500,
    category: 'newest',
  },
  {
    id: '29',
    SOID: '10',
    title: 'BBQ Tools Set',
    description: 'Stainless steel BBQ tools set',
    quantity: 10,
    price: 40,
    totalPrice: 400,
    category: 'tools',
  },
  {
    id: '30',
    SOID: '10',
    title: 'Picnic Blanket',
    description: 'Water-resistant picnic blanket',
    quantity: 12,
    price: 30,
    totalPrice: 360,
    category: 'common',
  },
];
