name: DEPLOY

on:
  workflow_call:
    inputs: # could be ${{ github.event.inputs.env }} or ${{inputs.env}}
      env:
        description: "Target deploy environment"
        type: string
        required: false
        default: 'dev'
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  setup-and-deploy:
    environment: ${{inputs.env}}
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: us-east-1
      AWS_REGION: us-east-1
    steps:
      - uses: actions/checkout@main

      - name: Configure AWS Credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region us-east-1

      - name: Get SSM Parameters as ENV variables
        run: |
          echo "WEBAPP_S3_BUCKET=$(aws ssm get-parameter --name /webapp/s3/bucket_name | jq '.Parameter.Value' -r)" >> "$GITHUB_ENV"
          echo "WEBAPP_CDN_DISTRIBUTION_ID=$(aws ssm get-parameter --name /webapp/cdn/distribution_id | jq '.Parameter.Value' -r)" >> "$GITHUB_ENV"

      - name: Get SSM Parameters as .env variables (for vite/dotenv)
        run: |
          echo "VITE_COGNITO_APP_CLIENT_ID=$(aws ssm get-parameter --name /campers/cognito_client_pool_id | jq '.Parameter.Value' -r)" >> .env
          echo "VITE_COGNITO_AWS_POOL_ID=$(aws ssm get-parameter --name /campers/cognito_user_pool_id | jq '.Parameter.Value' -r)" >> .env

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

      # - run: npm test

      - name: Build
        run: npm run build

      - name: Deploy
        run: |
          aws s3 sync dist/ s3://${{ env.WEBAPP_S3_BUCKET }} --delete
          aws cloudfront create-invalidation --distribution-id ${{ env.WEBAPP_CDN_DISTRIBUTION_ID }} --paths "/*"